### ISSUE TITLE
Test run keep failing

### ISSUE THREAD

**Issue by senramvx** [kbattenb/OrthoReD#4]
Hi, Dr. Battenberg

My name is Marcus, post-doc within Faderal University of Itajubá- Brazil and I'm trying to run OrthoReD, but test run (as suggested in readme file) keep ending with this following error:

marcus-senra@ubuntu:/media/marcus-senra/LabWork/Bioinformatics/OrthoReD/test$ bash INPUT_EXAMPLE/testrun_EXAMPLE.sh 
RUNNING SCRIPT: /media/marcus-senra/LabWork/Bioinformatics/OrthoReD/test/OrthoReD_v20180830 step-01-02.pl
(Procedure-00)Setting up the environment.
Following species are included in the species list:
	Arabidopsis thaliana
	Cucumis sativus
	Glycine max
	Mallus domestica
	Manihot esculenta
	Medicago truncatula
	Prunus persica
	Phaseolus vulgaris
	Vitis vinifera
Following files are included in the query:
	INPUT_EXAMPLE/At_rbcL.fas
(Procedure-01)Generate one quality-checked query file in single-line FASTA format.
Sequences with undetermined reading frame are removed.
0% of the sequences were removed.
(Procedure-02)Formatting directories.
SCRIPT COMPLETE
RUNNING SCRIPT: /media/marcus-senra/LabWork/Bioinformatics/OrthoReD/test/OrthoReD_v20180830 step-03-04.pl
(Procedure-00)Setting up the environment.
Following species are included in the species list:
	Arabidopsis thaliana
	Cucumis sativus
	Glycine max
	Mallus domestica
	Manihot esculenta
	Medicago truncatula
	Prunus persica
	Phaseolus vulgaris
	Vitis vinifera
Following files are included in the database:
	INPUT_EXAMPLE/dataset/Athaliana_subset.fas
	INPUT_EXAMPLE/dataset/Csativus_subset.fas
	INPUT_EXAMPLE/dataset/Gmax_subset.fas
	INPUT_EXAMPLE/dataset/Mdomestica_subset.fas
	INPUT_EXAMPLE/dataset/Mesculenta_subset.fas
	INPUT_EXAMPLE/dataset/Mtrucatula_subset.fas
	INPUT_EXAMPLE/dataset/Ppersica_subset.fas
	INPUT_EXAMPLE/dataset/Pvulgaris_subset.fas
	INPUT_EXAMPLE/dataset/Vvinifera_subset.fas
(Procedure-01)Foreach raw subject file, generate a quality-checked single-lined FASTA file.
processing:
	Step-03_Subjects_RAW/Gmax_subset.fas
	Step-03_Subjects_RAW/..
01_CLEANED/...
rsync: change_dir "/media/marcus-senra/LabWork/Bioinformatics/OrthoReD/test//Step-04_DATABASE/02_DATABASE" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
Couldn't open dir '/media/marcus-senra/LabWork/Bioinformatics/OrthoReD/test/Step-05_INPUT/DATABASE': No such file or directory at OrthoReD_v20180830/step-05-06.pl line 363.

I'm running a Ubuntu 20.04.2 LTS,  have all required programs installed and working and either NCBIBLAST and ABBLAST variables are set.

I was wondering if may have any thoughs on how to fix this. Thanks in advance.

**Comment by kbattenb** [comment]
Hi Marcus,

I am so glad that people are showing interested in using OrthoReD… Now I have to say, while I fully stand behind the theoretical basis of OrthoReD, I know that it is quite messy to work with it.
So I am sorry for that, but I will do the best I can to help you out here.

While I cannot reproduce on my end (I run a Mac and a CentOS), the issue seems to me come from step-03-04.pl not being able to properly recognize the list of multi-lined FASTA file.
So I made a modified version that captures the list of files in a different way.

Please go through the following steps to see if it works:
1. Replace your step-03-04.pl with the one I am attaching here.
2. Run the test and see if the list of files that it prints before it dies. (It is expected to die)
(If the list of file names matches what you see in Step-03_Subjects_RAW)
3-1. Open the new step-03-04.pl and remove line 285, remove all the intermediate files generated in the previous run, and rerun test.
(Else…)
3-2. Shoot me another message.

I hope this works out.



Kai Battenberg

**Comment by kbattenb** [comment]
Hi again Marcus,

Sorry, I just realized attaching a file on response does not work.
I created a test branch for you to get the modified step-03-04.pl 

Let me know how it goes.

Kai Battenberg

**Comment by senramvx** [comment]
Hi Kai!
Thanks for that fast reply!
I did what you asked and species names printed in the screen matched the files in Step-03_Subjects_Raw. So, I've removed line 285 from the script and re-run the analysis. However, it seems there is another problem... folder Step-06_ORTHOLOG is empty and, by the end of the code says "USAGE: AA database could not be identified".
Any thoughts?

Best regards,



marcus-senra@ubuntu:/media/marcus-senra/LabWork/Bioinformatics/OrthoReD/Test_Branch/OrthoReD/test$ bash INPUT_EXAMPLE/testrun_EXAMPLE.sh 
RUNNING SCRIPT: /media/marcus-senra/LabWork/Bioinformatics/OrthoReD/Test_Branch/OrthoReD/test/OrthoReD_v20180830 step-01-02.pl
(Procedure-00)Setting up the environment.
Following species are included in the species list:
	Arabidopsis thaliana
	Cucumis sativus
	Glycine max
	Mallus domestica
	Manihot esculenta
	Medicago truncatula
	Prunus persica
	Phaseolus vulgaris
	Vitis vinifera
Following files are included in the query:
	INPUT_EXAMPLE/At_rbcL.fas
(Procedure-01)Generate one quality-checked query file in single-line FASTA format.
Sequences with undetermined reading frame are removed.
0% of the sequences were removed.
(Procedure-02)Formatting directories.
SCRIPT COMPLETE
RUNNING SCRIPT: /media/marcus-senra/LabWork/Bioinformatics/OrthoReD/Test_Branch/OrthoReD/test/OrthoReD_v20180830 step-03-04.pl
(Procedure-00)Setting up the environment.
Following species are included in the species list:
	Arabidopsis thaliana
	Cucumis sativus
	Glycine max
	Mallus domestica
	Manihot esculenta
	Medicago truncatula
	Prunus persica
	Phaseolus vulgaris
	Vitis vinifera
Following files are included in the database:
	INPUT_EXAMPLE/dataset/Athaliana_subset.fas
	INPUT_EXAMPLE/dataset/Csativus_subset.fas
	INPUT_EXAMPLE/dataset/Gmax_subset.fas
	INPUT_EXAMPLE/dataset/Mdomestica_subset.fas
	INPUT_EXAMPLE/dataset/Mesculenta_subset.fas
	INPUT_EXAMPLE/dataset/Mtrucatula_subset.fas
	INPUT_EXAMPLE/dataset/Ppersica_subset.fas
	INPUT_EXAMPLE/dataset/Pvulgaris_subset.fas
	INPUT_EXAMPLE/dataset/Vvinifera_subset.fas
(Procedure-01)Foreach raw subject file, generate a quality-checked single-lined FASTA file.


Do the files listed below fit what you actually see in /media/marcus-senra/LabWork/Bioinformatics/OrthoReD/Test_Branch/OrthoReD/test/Step-03_Subjects_RAW?
	Athaliana_subset.fas
	Csativus_subset.fas
	Gmax_subset.fas
	Mdomestica_subset.fas
	Mesculenta_subset.fas
	Mtrucatula_subset.fas
	Ppersica_subset.fas
	Pvulgaris_subset.fas
	Vvinifera_subset.fas
processing:
	Step-03_Subjects_RAW/Athaliana_subset.fas
	Step-03_Subjects_RAW/Csativus_subset.fas
	Step-03_Subjects_RAW/Gmax_subset.fas
	Step-03_Subjects_RAW/Mdomestica_subset.fas
	Step-03_Subjects_RAW/Mesculenta_subset.fas
	Step-03_Subjects_RAW/Mtrucatula_subset.fas
	Step-03_Subjects_RAW/Ppersica_subset.fas
	Step-03_Subjects_RAW/Pvulgaris_subset.fas
	Step-03_Subjects_RAW/Vvinifera_subset.fas
(Procedure-02)From all the cleaned files, generate a database file.
Generating database file from:
	01_CLEANED/Athaliana_CLEANED.fas
	01_CLEANED/Csativus_CLEANED.fas
	01_CLEANED/Gmax_CLEANED.fas
	01_CLEANED/Mdomestica_CLEANED.fas
	01_CLEANED/Mesculenta_CLEANED.fas
	01_CLEANED/Mtrucatula_subset_CLEANED.fas
	01_CLEANED/Ppersica_CLEANED.fas
	01_CLEANED/Pvulgaris_CLEANED.fas
	01_CLEANED/Vvinifera_CLEANED.fas
Sequences with undetermined reading frame are removed.
0.02% of the sequences were removed from database.
Unique sequences from the following query file is included in the database:
	Step-02_QUERY/01_QUERY_QCD/QUERY.fas
creating a database from:
	02_DATABASE/EXAMPLE_DNA.fas

XDFORMAT 3.0 [2020-03-17] [linux-x64 2020-03-19T22:57:46]
Start:  2021-05-17T08:10:28
XDF Output Database:  EXAMPLE_DNA
 Alphabet:  NCBI2na.1
 Identifier index cache size:  1024 MiB
Input: "02_DATABASE/EXAMPLE_DNA.fas"
 No. of sequences (letters) written:  4500  (5,524,134)
 Longest sequence written (in database):  24,726  (24,726)
 Edit Alphabet:  WUStLna.1
 Sequences edited for ambiguity codes:  330
 No. of edits (total length) written:  2316  (32,397)
 Index entries written (in database):  4500  (4500)
Total cpu time:  0.02u 0.00s 0.02t   Elapsed:  00:00:00
End:  2021-05-17T08:10:28
XDFORMAT 3.0 [2020-03-17] [linux-x64 2020-03-19T22:57:46]
Start:  2021-05-17T08:10:28
XDF Output Database:  EXAMPLE_AA
 Alphabet:  NCBIstdaa.2
 Identifier index cache size:  1024 MiB
Input: "02_DATABASE/EXAMPLE_AA.fas"
 No. of sequences (letters) written:  4500  (1,841,378)
 Longest sequence written (in database):  8242  (8242)
 Index entries written (in database):  4500  (4500)
Total cpu time:  0.00u 0.02s 0.02t   Elapsed:  00:00:00
End:  2021-05-17T08:10:28
Database is generated.
(Procedure-03)Formatting directories.
SCRIPT COMPLETE
USAGE: AA database could not be identified.

**Comment by kbattenb** [comment]
Marcos,

Sorry again.
So it seems the perl command "readdir" is working differently in your system (or so it seems since these are the places where the script breaks).
Like the last time, I posted a patched step-05-06.pl that avoids the use of "readdir".

So one more time, please go through the following steps to see if it works:
1. Replace your step-05-06.pl with the patched one.
2. Run the test and see if the list of files that it prints before it dies. (It is expected to die)
(If the list of file names matches what you see in Step-05_INPUT/DATABASE)
3-1. Open the new step-05-06.pl and remove line 376, remove all the intermediate files generated in the previous run, and rerun test.
(Else…)
3-2. Shoot me another message.

Slowly but surely:)

Kai Battenberg

**Comment by senramvx** [comment]
Everything working fine now. Thank you!
Best regards,

Marcus
